---
title: "Reply"
output: 
<<<<<<< HEAD
  html_document:
    theme:
      version: 4
bibliography: PA.bib
---

Your comments are in blue, and our responses are in black.

<span style = "color: blue;">This study examines the economic value associated with three statistical methods used to generate site-specific nitrogen application rates: 1) geographically weighted regressions using the method of Rakshit et al. (2020) denoted as GWR-R, 2) geographically weighted regressions using the method of Trevisan et al. (2021) denoted as GWR-T, and 3) shape-constrained additive models (SCAM). Using straightforward Monte Carlo simulations, the two GWR methods are used to determine the economically optimal nitrogen rate (EONR) and profits from variable rate applications (VRA), while the SCAM methodology is used to determine the EONRs and profits for uniform rate applications (URA). These rates are based on estimations of site-specific corn yield functions for six cells across 1,440 subplots. The authors find the GWR-T outperforms GWR-R when the nitrogen price (relative to corn) is low, but GWR-R outperforms GWR-T when the nitrogen price is relatively high. This is because of the relative over- and underestimation of the EONRs. The study also finds that both GWR-T and GWR-R may have substantially overestimated the economic value of VRA; the net benefit of VRA over URA is much smaller, roughly $2 per acre (just over $5 per hectare, on average). For convenience, my review below is organized into a set of general comments, specific comments, and comments related to the exposition and writing, with each being arranged in order of page number. All comments are designed to strengthen the research.</span>  

We would like to express our sincere gratitude for the reviewer's careful examination and critique of our manuscript. The insightful comments and suggestions have significantly contributed to the paper's clarity, detail, and overall strength.  In return, we have attempted to carefully address each of the comments and revise the manuscript in response.

<br>

## <span style = "color: blue;">General Comments</span>  

<span style = "color: blue;">To some extent, this research is related to studies that examine the "value" of forecasting models by assessing their measure of inaccuracy. Given that determining the value of general regression methodologies is not overly common in the relevant literature here, why not add 1-2 paragraphs that ties your study to other studies that measure the "value" of certain econometric techniques?
</span>  

Thank you for bringing up this important point. What makes this study differ from previous studies is that the model “value” is not measured by the statistical accuracy of parameter estimates, but rather by the ultimate economic return. To emphasize this aspect, we have included an additional paragraph in the “5. Discussion and Conclusions” section (paragraph 2). It is worth noting that we are unable to identify a specific body of literature that exclusively focuses on assessing the value of general regression models. However, it is customary in the development of econometric models to evaluate their performance using statistical accuracy measures such as bias, mean squared error, and type I error, based on simulation data. We have referenced a few relevant studies of this nature to underscore the distinction of our economic value assessment approach.

<span style = "color: blue;">One of the most important questions in the literature relates to how variable rate technologies (VRT) can reduce negative externalities like fertilizer and chemical runoff and leaching. Clearly, this is not the research objective, and addressing a much more burning question in the literature would involve additional terms in the equation on p. 10, line 294 that represent the negative environmental externalities. The authors should clarify early on that "economically optimal" means "privately optimal" rather than "socially optimal."</span>  

Thank you for the suggestion. We have explicitly stated the following in a footnote at the end of the Introduction section of the revised manuscript: *"While the environmental impacts of fertilizer management are of great social importance, for simplicity we confine our analysis to its private economic impacts."*

<span style = "color: blue;">It strikes me as odd that, even with a minor clause on line 207 of p. 10, there is no real discussion of the corn price or nitrogen price in the methods section. What are the summary statistics and/or assumptions about p and w? What is the underlying intuition regarding the dependence of the relative performance of GWRR/GWRT to the corn-to-nitrogen price ratio (though this is partially explained in the paragraph on pages 15-16)? Any intuition about the ratios of 4.2, 5.4, and 10.4?</span>  

Thank you for bringing up this point. We have included a brief discussion of the historical corn and nitrogen prices in the first paragraph of the Results section 4.1. Additionally, we have included Appendix I: Historical Corn and Nitrogen Prices in the supplementary material to provide a more detailed description of the collection, calculation, and summary statistics of the historical price data. We also apologize for the typos of the price ratios 4.16, 5.44 and 10.35 in the previous version of the manuscript. The correct price ratios 5.44, 6.56, and 7.67 are used in the revised manuscript. The intuition underlying the dependence of the relative performances of GWRR and GWRT to the nitrogen-corn price ratio was explained in the paragraphs on pages 15-16 of the original manuscript, and that discussion has been included in the revised manuscript.  The main difference arises from the models' specifications of the coefficient on $N^2$.  The GWRR model allows for varying coefficient on $N^2$, leading to a wider range of estimated EONRs, while the GWRT model restricts the coefficient on $N^2$ to be constant, leading to a narrower range of estimated EONRs.  When nitrogen is expensive relative to corn, the true range of EONRs should be larger, and therefore the economic penalty of GWRR's over-estimation of EONR range will be smaller.  When the nitrogen-corn price ratio is lower, the true EONR range will be smaller, and GWRT's under-estimation of the EONR range is less of an issue. At the reviewer's request, we will be happy to further enhance the manuscript's discussion of this topic.

<span style = "color: blue;">Where is there no in-text reference to, or explanation of, Figure 4? I do not know what to make of this lone figure.</span>  

We apologize for the confusion. That figure was meant to compare the estimated and true GWR coefficients $\beta_1$ and $\beta_2$.  But since we have already compared the estimated and true EONR's in another figure, the figure 4 was redundant. We have removed it from the revised manuscript. 

<br>

## <span style = "color: blue;">Specific Comments</span>  

<span style = "color: blue;">P. 1, line 23: Site-specific farming, these days, does not have to be very precise, although the early literature conflated precision ag and site-specific farming. More importantly, VRT is just one component of precision ag; they are not synonymous.</span>  

We agree with the reviewer's comment that precision agriculture, site-specific farming, and variable-rate technology are not synonymous. Although in the literature those terms are often used interchangeably, they are not strictly speaking equivalent. We removed the statement in the parentheses "also known as site-specific farming, or variable-rate technology" to avoid misleading the audiences. 

<span style = "color: blue;">P. 5, lines 89-90: By this point, it would have been useful to add 1-2 sentences or a footnote about parallels with nonparametric estimators. Using multiple data points to derive local estimates, as in kernel density estimation, is nothing new. It would be helpful to provide more background on this. More broadly, at this point, besides the economics, why should we care about GWR relative to other spatial statistics methods?</span> 

We agree with the reviewer's comment that GWR is only one of many nonparametric estimators of local yield responses.  But our research goal was not to compare GWR with other estimators, nor to advocate the use of GWR.  We have tried to make this much more clear in the Introduction of the revised manuscript.  We explain as background that the GWR model has gained attention in developing site-specific input recommendations due to its minimal requirement of costly field characteristics data. We explain that our intent is to further test the value of having GWR available as a tool for the analysis of on-farm precision experimentation data and consequential input management recommendations. We do not intend to involve other spatial statistics methods in the current paper. But we do plan to conduct similar simulation-based economic evaluations of other local response estimation methods (such as the spatial kriging smoothing) in future research.

<span style = "color: blue;">P. 9, line 192: Here, do you mean that you set the 1370 kg ha-1 to be the square root of the sill variances?</span>  

Thanks for pointing out the typo. Yes, it should be the square root of the sill variances since 1370 kg ha−1 was the mean of the standard deviations. We have corrected that typo in the revised manuscript at the end of section 3.2.

<span style = "color: blue;">P. 11, line 220: At the first mention of shape-constrained additive models (SCAM), there should be a few sentences of explanation, either in the body or as a footnote. Even after the partial explanation on lines 232-233, it is still somewhat unclear and warrants more detail. The general readers of JAAEA are likely to not know, either.</span>  

Thank you for the suggestion. In section 3.5.1 of the revised manuscript we have expanded our explanation of SCAM to clarify that it is a regression model that can fit a more flexible and non-linear response relationship and also allows for shape constraints that can incorporate prior knowledge or theories.

<span style = "color: blue;">Pp. 11-12, lines 238-245: To check, l=K, i.e., the total number of splines from the equation on line 238 equals the total number of splines used for f ̂_SCAM (∙)? If so, use the same notation.</span>

Yes, the $l$ and $k$ should have been the same. We use $k$ in the revised manuscript.

<span style = "color: blue;">P. 13, lines 268-270: How robust are the N^*_{GWR-T,j} rates to variations in the AIC-chosen bandwidth parameters? More information about this needs to be provided.</span>  

If we understand the question correctly, you are asking about the robustness of GWR estimates to bandwidth selection. Choosing bandwidth is indeed a crucial step in GWR estimation, and there are many different bandwidth selection methods in the literature. In this study we used the corrected version of AIC approach [@fotheringham2017multiscale; @lu2017geographically] to determine the optimal bandwidth. It is a commonly used approach in practice, and also the same approach used by @rakshit2020 and @trevisan2021spatial which can make our simulation evaluations consistent. Since the corrected AIC method generates a unique bandwidth, we did not conduct any robustness check to bandwidths. We agree the GWR results could vary when choosing different bandwidths, but the choices of other bandwidth values other than the AIC-chosen one may be arbitrary. We added more discussions about bandwidth selection at the end of section 3.5.3 of the revised manuscript.

<span style = "color: blue;">P. 15, lines 303-305: Why are the numbers from these sentences blank? In particular, the median benefit of VRA under GWRR is ? and the median benefit of VRA under GWRT is…?</span>  

Our apologies for the typos. We have corrected them and filled in the correct numbers. They can be found in the end of the 2nd paragraph of section 4.1 of the revised manuscript.

<span style = "color: blue;">P. 15: You first discuss figure 6 and then move to figure 5. Put all figures in order.</span>  

Thank you for identifying the incorrect order of figures. We apologize for the mistake, and we have corrected the order of the figures accordingly. The revised manuscript now reflects the correct sequence of the two figures. Note that since the original Figure 4 was removed, the two figures are now the new Figure 4 and Figure 5.

<br>

## <span style = "color: blue;">Writing</span>  

<span style = "color: blue;">P. 2, line 45: This should be "data are", not "data is". </span>  

This grammar error was corrected. The new sentence is now on section 2.2, the 1st paragraph, line 2 of the revised manuscript.

<span style = "color: blue;">P. 2, line 52: Basically or actually? Vagueness here makes it difficult to assess the degree to which OSU's calculators are being used directly. </span>  

We removed the word "basically" in the pertinent part of the revised manuscript.

<span style = "color: blue;">P. 2, line 54: To avoid confusing a general agricultural economics audience, I would use an abbreviation other than Rx for site-specific recommendations. </span>  

In precision agriculture, the site-specific input management recommendation map is commonly called "prescription" or "Rx" by researchers and the industry. While we are certainly willing to defer to the editor's judgment, we have elected to keep this abbreviation in the revised manuscript, but have added a brief explanation of the notation (in the 1st paragraph of section 2.2). In the USA, at least, it is widely known that "Rx" means "prescription," and it is chiefly used in conversations about medicines and pharmacies.

<span style = "color: blue;">P. 2, lines 49-60: All of these current commercial examples would work better as a footnote as they may become inaccurate in the next 3-10 years (or fewer). </span>  

Thank you for the suggestion. We agree that precision agriculture technologies are advancing rapidly. However, we believe that those commercial examples are essential to illustrate the current state of site-specific field data collection technologies, which will help readers understand the benefits of the GWR method. Therefore, we prefer to retain these examples in the main text. Nonetheless, we acknowledge that these contents may be a little lengthy, so we have moved them from the Introduction section to the Background section of 2.2 (1st paragraph).

<span style = "color: blue;">P. 5, lines 91-114: This page-long paragraph should be split up into at least two paragraphs. The length is taxing. I would consider starting a new paragraph with the sentence beginning on line 97.</span>  

This paragraph's contents were broken into two pieces in the revised manuscript, one piece in the last paragraph of Introduction section, and the other piece in the first paragraph of section 2.3. 

<span style = "color: blue;">P. 7, line 137: This comment should have been removed by the authors prior to manuscript submission.</span>  

This typo has been removed. Thank you for bringing it to our attention.

<span style = "color: blue;">P. 9, line 189: The acronym DIFM is used before it's spelled out in the sentence, but you should spell it out first and then use the acronym. </span>  

Thank you for pointing out this writing issue. We have placed the acronym DIFM after the full name in the revised manuscript.

<span style = "color: blue;">P. 10, line 212: The (j,k) index should be subscripted here.</span>  

We greatly appreciate the reviewer's meticulous review of the manuscript and for finding this typo. We have corrected it to use subscript notation (see line 3 of section 3.4). Furthermore, to eliminate the duplication of the spline index $k$, we have updated the cell index notation to $(j, i)$ both in this section and throughout the rest of the manuscript.

<span style = "color: blue;">P. 11, line 221: The second "and" should be "an". </span>  

The typo is corrected. Thank you so much for finding this typo.

<span style = "color: blue;">P. 11, line 232: Are you using one shape constraint or more than one shape constraint? The language here really matters so as to avoid confusion on the part of the readers.</span>  

Here we are modeling a "full-field" response function.  That is, the model assumes that yield response is uniform across the field.  We agree that the language used could cause confusion about whether we were referring to the yield response function or the shape constraint as "single."  We removed the term "single" from the revised manuscript.  Please see section 3.5.1 of the revised manuscript.

<span style = "color: blue;">P. 11, line 235: It seems that 1-2 citations could be added (or are missing) after "well substantiated by agronomic research."</span>  

We have cited two additional of agronomic studies (Bullock and Bullock, 1994; Cerrato and Blackmer, 1990) to support the statement in section 3.5.1 of the revised manuscript.

<span style = "color: blue;">P. 12, line 253: I know what you mean by the notation f ̂_(GWR-R,j) (N), but the hyphen in the notation almost seems like a subtraction sign. I would recommend changing GWR-R and GWR-T to GWRR and GWRT and then having superscripts here. That is, f ̂_j^GWRR (∙) and f ̂_j^GWRT (∙).</span>  

Thank you for the recommendation. We have changed GWR-R and GWR-T GWRR and GWRT throughout the revised manuscript.  We have also put all model names (GWR and SCAM) in superscripts in the pertinent equations.

<span style = "color: blue;">P. 13, line 271: In keeping with your past usage, you should make sure the acronym SCAM is in uppercase throughout the text.</span>  

Thank you for pointing out this formatting error. We have corrected the issue by ensuring that the acronym “SCAM” is consistently written in uppercase throughout the text. Additionally, we have capitalized all acronyms in equations as well.

<span style = "color: blue;">P. 15, line 304: "but the its benefit is even negative at when the" should have the typos/redundant wording removed.</span>  

Thank you for pointing out those typos. They have all been corrected (see the end of the 2nd paragraph of section 4.1 of the revised manuscript).

<span style = "color: blue;">P. 17, line 335: Figure 0?</span>  

Our apologies for the typo. It should have been Figure 5 and this problem is fixed in our new manuscript (see the 2nd paragraph of section 4.2).

<span style = "color: blue;">P. 18, line 362: Section title should just be "Discussion". </span>  

We have combined what were the two final sections of the original manuscript into one section, headed “Discussion and Conclusions.”

<span style = "color: blue;">P. 34, Figure 8 horizontal axis label: "Estiamated" should be "Estimated". </span>

We greatly appreciate the reviewer for identifying this typo. It was corrected in the revised manuscript (now Figure 7).

<span style = "color: blue;">Pp. 19-20, lines 398-400: Can this sentence be sharpened? Right now, it is a bit too vague to be completely useful as a guide to researchers in this area. Specifically, what other statistical estimators should be reconsidered and how (specifically) should they be reassessed?</span>  

We have edited the sentence in the revised manuscript (near the end of paragraph 4, section 5 in the revised manuscript), adding details to explain that other statistical methods commonly used for site-specific yield response estimation literature include regression on field characteristics variables as interaction terms, machine learning, etc. The common assessment approach is to use simulation-based evaluation, much as we do in our study.
=======
  html_document: default
---

Your comments are in blue.  Our responses are in black.

# General Comments

+ <span style = "color: blue;">I still believe this research is related to studies that examine the economic value of forecasting models by assessing the economic effects stemming from inaccuracy (e.g.,
reduction in a business’ profits by assuming a mean-squared-error loss function instead of an
asymmetric loss, for example). Although there have been improvements in references to the
agronomy and statistical literatures, it would still be useful to add 1-2 sentences in the
conclusion that reference the broader economics literature on this topic. </span> 

Response: We do not address this as you suggested.

+ <span style = "color: blue;"> As mentioned in my previous review, the term "economically optimal" has different meanings among agricultural economists. The new footnote (footnote 1 on p. 5) is appreciated, but here you should specify that "economically optimal" in the context of the article does not mean "socially optimal."</span> 

Response:

+ <span style = "color: blue;"> None of the figure numbers appear in the text; instead, each figure reference is followed by "Error! Reference source not found." These all should be corrected. </span>

Response: 


+ <span style = "color: blue;"> In Section 3, to reduce confusion, you should consider using the word "Simulated" in the section heads (i.e., 3.1 Simulated Field Layout, 3.2 Simulated True Cell-Specific Yield Response Function, 3.3 Simulated Trial Design, and 3.4 Simulated Yield Data). </span> 

Response: Instead of making the suggested changes, we simply renamed the Methods section to "Methods: Monte Carlo Simulations," so that it is clear that all the subsequent sections are about simulations.

+ <span style = "color: blue;"> All of the figures have their dimensions and DPI listed (1422x812mm). This information is not necessary and should have been removed prior to submission. </span> 

Response: We apologize this mistake. This has been fixed in this version of the manuscript.

# Specific Comments

+ <span style = "color: blue;"> P. 4, lines 58-59: This statement, while perhaps likely, is just speculation. The authors should either check with Trevisan et al. (2021) that this was the reason (and then remove "It seems likely") or just delete the sentence entirely. The same comment applies to P. 8, lines 134-136. </span> 

Response: You are correct and we have removed the sentence entirely.

+ <span style = "color: blue;">P. 6, lines 91-95: Implicitly, you seem to be suggesting that the set of points from which you would take (input rate, yield) data is smaller than n, the total number of sites associated with the characteristics vector. Either way, this should be clarified in the text.</span> 

Response: We have modified the sentence to the following so that it describes what GWR does more accurately:

  - Old: "Alternatively, a site-specific yield response function might be estimated simply by taking (input rate, yield) data from points around a site of interest"
  - New: "Alternatively, a site-specific yield response function might be estimated simply by giving greater weights to the points around a site of interest"

+ <span style = "color: blue;"> P. 9, lines 146-148: This seems overly negative of Trevisan et al. (2021), as well as clunky wording ("provided an example at step 3"). Since you say this assumption is unavoidable, it is done by all studies, including the ones you mention above: Anselin et al, Bullock et al, Liu et al, and Swinton and Lowenberg-DeBoer. You should remove this sentence entirely because it really adds nothing. Later on in the paragraph, you address the thing that's more important: inaccurate estimation of yield response using GWR, because it exaggerates the true heterogeneity in the yield response functions, leads to comparatively worse bias. </span>

Response: We dropped the sentence.

+ <span style = "color: blue;"> P. 10, lines 185-186: This almost sounds misleading; "were available for analysis" seems to suggest you were using real-world data. You should re-write this as "In total, simulated data from 1,440 subplots were used for analysis." </span>

Response: We edited the sentence according to your suggestion.

+ <span style = "color: blue;"> P. 10, line 199: In this sentence, you should mention which specific statistical distribution the error term follows, despite the fact that you mention Gaussian random fields below. </span> 

Response: It follows a normal distribution in a way it is spatially correlated. This has been made clear in the manuscript (see page ??, line ??). 

+ <span style = "color: blue;">P. 12, line 212: It would be useful to add a footnote here explaining why the range of 600m was chosen.</span> 

Response:

+ <span style = "color: blue;">P. 12, line 229: Given that JAAEA is an economics journal and not an agronomy journal, you should rewrite "Latin square trial design schema" as "trial design" here, and at the end of the next sentence, write "each column of the block (i.e., a Latin square)." </span> 

Response: We followed your suggestions and texts were modified accordingly.

+ <span style = "color: blue;">P. 14, line 254: For additional clarity, you could point out that the EONR rate is just the value of N that solves $\\cdot f(N) - \omega\dcot N$, where $f(N)$ is SCAM-estimated. </span>

Response:

+ <span style = "color: blue;"> P. 15, lines 277-279: Add a sentence (perhaps in a footnote) mentioning how this shape constraint is actually imposed. </span> 

Response:

+ <span style = "color: blue;">PP. 22-23, lines 439-441: This sentence should be removed because it seems speculative. More importantly, researchers do not "have" to implement a methodology because it is conveniently available in standard software; instead, they could code their own models, methods, etc.  </span> 

Response:

+ <span style = "color: blue;">P. 33, Figure 2: In the notes to this figure, you should add that the 1,440 subplots are illustrated as 24 rows x 12 columns, each containing 5 subplots (24 x 12 x 5 = 1,440). Also add that there are 72 rows x 120 columns of cells (72 x 120 = 8,640).  </span> 

Response:


Writing

+ P. 4, line 45: Replace "dramatic" with "seemingly implausibly large"

Response:

+ P. 4, line 54: Replace "suspect" with "hypothesize"
o Same comment for "suspect" on P. 9, line 153

Response:

+ P. 5, line 77: You do not need to write (OFPE) again here since you have already introduced
the acronym.

Response:

+ P. 8, line 124: You should place the first instance of "(EONR)" here after "economically
optimal nitrogen rates" rather than line 132.

Response:

+ P. 8, line 130: Replace "dangerous" with "problematic"
o Same comment for P. 22, line 438

Response:

+ P. 8, line 145: Remove the word "the" in front of "step"

Response:

+ P. 11, lines 200-201: Replace "are desirable properties" with "is a desirable property"

Response:

+ P. 13, line 233: Replace "due the" with "due to the"

Response:

+ P. 14, line 262: This is the first and only mention in the paper of a benchmark. Given that,
what is a "lower" benchmark?

Response:

+ P. 16, line 295: Replace "as" with "the"

Response:

+ P. 19, line 269: Replace "truea" with "true"

Response:

+ P. 22, line 453: Remove the word "please"

Response:

+ P. 24, lines 468-474: Remove the clause "After the development of software that..."
Additionally, you should add quotation marks to both instances of "pure" in this paragraph.
Response:


>>>>>>> origin/master
