---
output:
  word_document: default
  html_document: default
---
# Reply to the Reviewer #2

Your comments are in blue, and our responses are in black.

<span style = "color: blue;">This study examines the economic value associated with three statistical methods used to generate site-specific nitrogen application rates: 1) geographically weighted regressions using the method of Rakshit et al. (2020) denoted as GWR-R, 2) geographically weighted regressions using the method of Trevisan et al. (2021) denoted as GWR-T, and 3) shape-constrained additive models (SCAM). Using straightforward Monte Carlo simulations, the two GWR methods are used to determine the economically optimal nitrogen rate (EONR) and profits from variable rate applications (VRA), while the SCAM methodology is used to determine the EONRs and profits for uniform rate applications (URA). These rates are based on estimations of site-specific corn yield functions for six cells across 1,440 subplots. The authors find the GWR-T outperforms GWR-R when the nitrogen price (relative to corn) is low, but GWR-R outperforms GWR-T when the nitrogen price is relatively high. This is because of the relative over- and underestimation of the EONRs. The study also finds that both GWR-T and GWR-R may have substantially overestimated the economic value of VRA; the net benefit of VRA over URA is much smaller, roughly $2 per acre (just over $5 per hectare, on average).  

For convenience, my review below is organized into a set of general comments, specific comments, and comments related to the exposition and writing, with each being arranged in order of page number. All comments are designed to strengthen the research.</span>  
General reply: We would like to express our sincere gratitude for the reviewer's careful and thorough review of our research paper. The insightful comments and suggestions have significantly contributed to improving the clarity, detail, and overall strength of our manuscript. We truly appreciate the time and effort the reviewer has dedicated to this review process. We have carefully addressed each of the comments and incorporated the necessary revisions into the manuscript.  

<br>


<span style = "color: blue;">General Comments</span>  

<span style = "color: blue;">To some extent, this research is related to studies that examine the “value” of forecasting models by assessing their measure of inaccuracy. Given that determining the value of general regression methodologies is not overly common in the relevant literature here, why not add 1-2 paragraphs that ties your study to other studies that measure the “value” of certain econometric techniques?
</span>  
Reply: Thank you for bringing up this important point. A significant aspect that sets this study apart from many previous studies lies in the evaluation of econometric models, where this study's measures are not based on the statistical accuracy of parameter estimates, but rather on the ultimate economic returns generated by the models. To emphasize this aspect, we have included an additional paragraph in the "Discussion and Conclusions" section (page x, lines xxx). It is worth noting that we were unable to identify a specific body of literature that exclusively focuses on assessing the value of general regression models. However, it is customary in the development of econometric models to evaluate their performance using statistical accuracy measures such as bias, mean squared error, and type I error, based on simulation data. We have referenced a few relevant studies of this nature to underscore the distinction of our economic value assessment approach.

<span style = "color: blue;">One of the most important questions in the literature relates to how variable rate technologies (VRT) can reduce negative externalities like fertilizer and chemical runoff and leaching. Clearly, this is not the research objective, and addressing a much more burning question in the literature would involve additional terms in the equation on p. 10, line 294 that represent the negative environmental externalities. The authors should clarify early on that “economically optimal” means “privately optimal” rather than “socially optimal.”</span>  
Reply: Thank you for the suggestion of clarifying the definition of "economically optimal". We added some explicit description in the introduction section (page xx, lines xxx) that the economical optimization in this study only includes farmers' private profit, and environmental externalities are not considered in this study.

<span style = "color: blue;">It strikes me as odd that, even with a minor clause on line 207 of p. 10, there is no real discussion of the corn price or nitrogen price in the methods section. What are the summary statistics and/or assumptions about p and w? What is the underlying intuition regarding the dependence of the relative performance of GWRR/GWRT to the corn-to-nitrogen price ratio (though this is partially explained in the paragraph on pages 15-16)? Any intuition about the ratios of 4.2, 5.4, and 10.4?</span>  
Reply: Thank you for bringing up this point regarding the discussion of price information in the study. We have included a brief discussion of the historical corn and nitrogen prices in the results section (page x, lines xxx), explaining the three ratios represented the historically low, middle, and high price ratio scenarios. Additionally, we have created an appendix in the supplementary material (Appendix I: Historical Corn and Nitrogen Prices) to provide a more detailed description of the collection, calculation, and summary statistics of the historical price data. We also apologize for the typos of the price ratios 4.16, 5.44 and 10.35 in the previous version manuscript. The correct price ratios should be 5.44, 6.56, and 7.67. They were all corrected in the revised manuscript.  

For the underlying intuition regarding the dependence of relative performance of GWRR/GWRT to the nitrogen-corn price ratio, as explained in the paragraphs on pages 15-16 of the original manuscript, we believe the main difference arises from the specification of the $N^2$ coefficient in the models The GWRR model allows for a varying coefficient on $N^2$, leading to a wider range of estimated EONRs, while the GWRT model restricts the $N^2$ to be constant, leading to a narrower range of estimated EONRs. At higher nitrogen-corn price ratio, where nitrogen is relatively more expensive, the true range of EONRs should be larger, and therefore the economic penalty of GWRR's over-estimation of EONR range will be smaller. On the opposite, at lower nitrogen-corn price ratio, the true EONR range will be smaller, and the GWRT's under-estimation of EONR range is less of an issue. We believe this explanation adequately addresses the intuition behind the observed results. However, if the reviewer feels that further clarification is needed, please let us know, and we will be more than willing to provide additional discussion to enhance the understanding of our findings.

<span style = "color: blue;">Where is there no in-text reference to, or explanation of, Figure 4? I do not know what to make of this lone figure.</span>  
Reply: We sincerely apologize for this oversight. The figure was originally included to compare the estimated and true GWR coefficients $\beta_1$ and $\beta_2$. However, as we have already compared the estimated and true EONRs in the subsequent figure, the coefficient comparisons are no longer necessary. Regrettably, we forgot to remove it from the final manuscript. We have now rectified this mistake and removed the figure accordingly. Thank you for bringing it to our attention.
(__Taro: I removed that figure. Is it OK? Or you still want to keep it and say something about it?__)

<br>


<span style = "color: blue;">Specific Comments</span>  

<span style = "color: blue;">P. 1, line 23: Site-specific farming, these days, does not have to be very precise, although the early literature conflated precision ag and site-specific farming. More importantly, VRT is just one component of precision ag; they are not synonymous.</span>  
Reply: We agree with the reviewer's comment that precision agriculture, site-specific farming, and variable-rate technology are not the same thing. Although in the literature those terms are often used interchangeably, they are not strictly speaking equivalent. We removed the statement in the parentheses "also known as site-specific farming, or variable-rate technology" to avoid misleading the audiences. 

<span style = "color: blue;">P. 5, lines 89-90: By this point, it would have been useful to add 1-2 sentences or a footnote about parallels with nonparametric estimators. Using multiple data points to derive local estimates, as in kernel density estimation, is nothing new. It would be helpful to provide more background on this. More broadly, at this point, besides the economics, why should we care about GWR relative to other spatial statistics methods?</span>  
Reply: We agree with the reviewer's comment that there are many nonparametric estimators that can estimate local yield responses, among which GWR is only one of them. However, the goal of this study is not to compare GWR with other estimators or to advocate the use of GWR. As stated  in the introduction section (page 1, lines 41-42xx; page 2, lines 61-65xx), the background of this study is that GWR model has gained attention in developing site-specific input recommendations due to its minimum requirement of costly field data collection. Our interest is to further test whether GWR is truly economically viable in this application and provide guidance for precision farming practice. The current study does not intend to involve other spatial statistics methods. But we do have plans to conduct similar simulation-based economic evaluations of other local response estimation methods (such as the spatial kriging smoothing) in future research.  

<span style = "color: blue;">P. 9, line 192: Here, do you mean that you set the 1370 kg ha-1 to be the square root of the sill variances?</span>  
Reply: We apologize for the typo. Yes, it should be the square root of the sill variances since 1379 kg ha$^{-1}$ was the mean of standard deviations. Thank you for pointing out this typo. We have corrected that statement (see page x, line xx in the revised manuscript).

<span style = "color: blue;">P. 11, line 220: At the first mention of shape-constrained additive models (SCAM), there should be a few sentences of explanation, either in the body or as a footnote. Even after the partial explanation on lines 232-233, it is still somewhat unclear and warrants more detail. The general readers of JAAEA are likely to not know, either.</span>  
Reply: Thank you for the suggestion. We added a few more explanations of the SCAM (see page xx, lines xxx of the revised manuscript) to make it more clear to the general JAAEA readers that it is a regression model that can fit a more flexible and non-linear response relationship, and also allows for shape constraints that can incorporate prior knowledge or theories. 

<span style = "color: blue;">Pp. 11-12, lines 238-245: To check, l=K, i.e., the total number of splines from the equation on line 238 equals the total number of splines used for f ̂_SCAM (∙)? If so, use the same notation.</span>  
Reply: Thank you for pointing out this typo of notations. Yes, the $l$ and $k$ should be the same. We corrected the notations to use $k$ in the revised manuscript.

<span style = "color: blue;">P. 13, lines 268-270: How robust are the N ̂_(GWR-T,j )^*rates to variations in the AIC-chosen bandwidth parameters? More information about this needs to be provided.</span>  
Reply: If we have correctly understood the question, it pertains to the robustness of GWR estimates with respect to bandwidth selection. We acknowledge that choosing the appropriate bandwidth is a critical step in GWR estimation, and the literature offers numerous methods for bandwidth selection. In our study, we employed the corrected version of the AIC approach as proposed by Fotheringham et al. [@fotheringham2017multiscale; @lu2017geographically] to determine the optimal bandwidth. This approach is widely used in practice and aligns with the methodology employed by Rakshit et al. [@rakshit2020] and Trevisan et al. [@trevisan2021spatial], thereby ensuring consistency in our simulation evaluations. 

As the corrected AIC method results in a unique bandwidth, we did not conduct additional robustness checks on alternative bandwidth values. While we acknowledge that GWR results may vary when using different bandwidths, selecting bandwidths other than the one determined by the AIC approach could introduce arbitrariness. Nevertheless, we have provided additional discussions about bandwidth selection in more depth in the revised manuscript on page x, lines xxx to provide more details and clarifications.

<span style = "color: blue;">P. 15, lines 303-305: Why are the numbers from these sentences blank? In particular, the median benefit of VRA under GWRR is ? and the median benefit of VRA under GWRT is…?</span>  
Reply: We apologize for the oversight in the sentences with blank numbers. We have rectified the issue by correcting the typos and providing the missing numbers. You can find the updated information on page x, line xx in the revised manuscript. Thank you for bringing this to our attention.

<span style = "color: blue;">P. 15: You first discuss figure 6 and then move to figure 5. Put all figures in order.</span>  
Reply: Thank you for identifying the incorrect order of Figures 5 and 6. We apologize for the mistake, and we have corrected the order of the figures accordingly. The revised manuscript now reflects the correct sequence of Figures 5 and 6.

<br>


<span style = "color: blue;">
Writing
</span>  

<span style = "color: blue;">P. 2, line 45: This should be “data are”, not “data is”. </span>  
Reply: This grammar error was corrected. The new sentence is now on page xx, line xx of the revised manuscript.

<span style = "color: blue;">P. 2, line 52: Basically or actually? Vagueness here makes it difficult to assess the degree to which OSU’s calculators are being used directly. </span>  
Reply: The term "basically" used in that context does appear informal and imprecise. In the revised manuscript, we have removed the term "basically" (see page x, line xxx) to ensure clarity and eliminate any potential confusion.

<span style = "color: blue;">P. 2, line 54: To avoid confusing a general agricultural economics audience, I would use an abbreviation other than Rx for site-specific recommendations. </span>  
Reply: In precision agriculture, the site-specific recommendation map is commonly referred to as a "prescription" or denoted as "$R_x$" by both researchers and industry professionals. While there may be other abbreviations in use, they are not as widely recognized as "$R_x$". To ensure clarity for readers who may not be familiar with precision agriculture terminology, we have included a brief note explaining that "$R_x$" represents "prescription" when it is first mentioned (page x, line xxx in the revised manuscript). This clarification aims to make the meaning of the abbreviation clear to a broader agricultural economics audience.

<span style = "color: blue;">P. 2, lines 49-60: All of these current commercial examples would work better as a footnote as they may become inaccurate in the next 3-10 years (or fewer). </span>  
Reply: Thank you for the suggestion. We agree that placing the commercial examples in a footnote is a better approach. As per your suggestion, all the relevant content has been moved to footnote 1 on page xx of the revised manuscript.

<span style = "color: blue;">P. 5, lines 91-114: This page-long paragraph should be split up into at least two paragraphs. The length is taxing. I would consider starting a new paragraph with the sentence beginning on line 97.</span>  
Reply: Thank you for the suggestion. We have followed this suggestion and divided the discussion into two paragraphs. The second paragraph now begins on page x, line xx. Additionally, we have made slight wording changes to the beginning of this paragraph to enhance clarity and coherence.

<span style = "color: blue;">P. 7, line 137: This comment should have been removed by the authors prior to manuscript submission.</span>  
Reply: This typo has been removed. Thank you for bring it to our attention.

<span style = "color: blue;">P. 9, line 189: The acronym DIFM is used before it’s spelled out in the sentence, but you should spell it out first and then use the acronym. </span>  
Reply: Thank you for pointing out this writing issue. We have addressed it by placing the acronym DIFM after its full name, as suggested. The revised placement can be found on page x, line xx.

<span style = "color: blue;">P. 10, line 212: The (j,k) index should be subscripted here.</span>  
Reply: We greatly appreciate the reviewer's meticulous review of the manuscript and for finding this typo. We have corrected it to use subscript notation (see page x, line xx). Furthermore, to eliminate the duplication of the spline index $k$, we have updated the cell index notation to ($j$, $i$) both in this section and throughout the rest of the manuscript.

<span style = "color: blue;">P. 11, line 221: The second “and” should be “an”. </span>  
Reply: The typo is corrected. Thank you so much for finding this typo.

<span style = "color: blue;">P. 11, line 232: Are you using one shape constraint or more than one shape constraint? The language here really matters so as to avoid confusion on the part of the readers.</span>  
Reply: The model described here is a single yield response function for the full field. In other words, there is only one uniform response rather than variable responses. We acknowledge that the language used may have caused confusion regarding whether it refers to a "single" response function or a "single" shape constraint. To address this concern and eliminate any ambiguity, we have removed the term "single" from the manuscript (see page x, line xx in the revised version).

<span style = "color: blue;">P. 11, line 235: It seems that 1-2 citations could be added (or are missing) after “well substantiated by agronomic research.”</span>  
Reply: We followed the comment and added two citations of agronomic studies to support this statement (see page x, line xx in the revised manuscript).

<span style = "color: blue;">P. 12, line 253: I know what you mean by the notation f ̂_(GWR-R,j) (N), but the hyphen in the notation almost seems like a subtraction sign. I would recommend changing GWR-R and GWR-T to GWRR and GWRT and then having superscripts here. That is, f ̂_j^GWRR (∙) and f ̂_j^GWRT (∙).</span>  
Reply: Thank you for the recommendation. We also agree that "GWRR" and "GWRT" appear more concise than "GWR-R" and "GWR-T", and have made the changes as recommended. Additionally, we have placed all model names (GWR and SCAM) in superscripts in the equations. We appreciate the reviewer's comment, which has helped us improve the consistency of our notations across the manuscript.

<span style = "color: blue;">P. 13, line 271: In keeping with your past usage, you should make sure the acronym SCAM is in uppercase throughout the text.</span>  
Reply: Thank you for pointing out this formatting error. We have corrected the issue by ensuring that the acronym "SCAM" is consistently written in uppercase throughout the text. Additionally, we have capitalized all acronyms in equations as well. 

<span style = "color: blue;">P. 15, line 304: “but the its benefit is even negative at when the” should have the typos/redundant wording removed.</span>  
Reply: Thank you for pointing out those typos. They have all been corrected (see page x, line xx in the revised manuscript).

<span style = "color: blue;">P. 17, line 335: Figure 0?</span>  
Reply: We apologize for the typographical error. It should be Figure x. (__Taro: Which figure are you referring to here? I don't think it should be Figure 5.__)

<span style = "color: blue;">P. 18, line 362: Section title should just be “Discussion”. </span>  
Reply: The title has been changed to “Discussion”. Furthermore, we combined this section with the conclusions section, and the new title is "Discussion and conclusions".

<span style = "color: blue;">P. 34, Figure 8 horizontal axis label: “Estiamated” should be “Estimated”. </span>  
Reply: We greatly appreciate the reviewer for identifying this typo. It was corrected in the revised manuscript.

<span style = "color: blue;">Pp. 19-20, lines 398-400: Can this sentence be sharpened? Right now, it is a bit too vague to be completely useful as a guide to researchers in this area. Specifically, what other statistical estimators should be reconsidered and how (specifically) should they be reassessed?</span>  
Reply: We sincerely appreciate the reviewer's feedback regarding the vagueness of this sentence. We added more details to explain that the other commonly used statistical methods in the site-specific yield response estimation literature include the regression with interaction terms of field characteristics, machine learning, etc. The assessment approach will be simulation-based evaluation that is similar to the one used in this study. (See page x, line xx in the revised manuscript.)


__Other notes__  
1. Subscript (j,k) changed to (j,i). k is already used in spline notation.  
2. Title of figures. Explicitly add what low, middle, and high mean so the reader do not need to go back to the main text to search the definitions.  
3. Figure number on P. 17, line 335?